---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: cert-manager-repo
spec:
  interval: 24h # Update the Artifact every 24h
  url: https://charts.jetstack.io
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
spec:
  interval: 30m # Check the changes in this release-file itself every 30 mins
  chart:
    spec:
      chart: cert-manager
      # version: 4.6.x
      sourceRef:
        kind: HelmRepository
        name: cert-manager-repo
      interval: 12h # Check for changes in the Chart every 12h
  
  timeout: 20m # Installation of a component shouldn't exceed this

  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
  install:
    remediation:
      retries: 3
      remediateLastFailure: true
    
  ## Provide Values for Chart
  values:
    prometheus:
      enabled: false
    podDnsPolicy: "None"
    podDnsConfig:
      nameservers:
        - "1.1.1.1"
        - "8.8.8.8"
