apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: av-server-external-secrets
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: av-server-secrets
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: av-server