apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: aws-s3-external-secrets
spec:
  refreshInterval: "3600s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: aws-s3-credentials
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: aws-s3-bucket