apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: "https://vaultui-central.saifty.coacapp.de"
      path: "heraeus-dev" # Different for different environments
      version: "v2"
      auth:
        tokenSecretRef:
          name: "vault-token" # Flux DOES NOT create this secret. Make sure this secret is present before installing using flux"
          key: "token"
          namespace: "external-secrets"