apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: filestorage-external-secrets
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: filestorage-secrets
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: filestorage
  - extract:
      key: auth