apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: saifty-helm-external-secrets
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: saifty-helm-repo-secret
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: saifty-helm-chart