apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nifi-external-secrets
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: nifi-admin-credentials
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: nifi-admin-credentials