apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: rate-limiter-external-secrets
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: rate-limiter-secrets
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: rate-limiter
  - extract:
      key: auth