apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: robots-wrapper-external-secrets
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: robots-wrapper-secrets
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: robots-wrapper