apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sap-gateway-external-secrets
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: sap-gateway-secrets
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: sap-gateway