apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sds-ocr-external-secrets
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: sds-ocr-secrets
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: sds-ocr-worker
  - extract:
      key: auth0
  - extract:
      key: microsoft_auth