---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: ingress-nginx-repo
spec:
  interval: 24h
  url: https://kubernetes.github.io/ingress-nginx
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
spec:
  interval: 30m # Check the changes in this release-file itself every 30 mins
  chart:
    spec:
      chart: ingress-nginx
      # version: 4.6.x
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx-repo
      interval: 12h # Check for changes in the Chart every 12h
  
  timeout: 20m # Installation of a component shouldn't exceed this

  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
  install:
    remediation:
      retries: 3
      remediateLastFailure: true
    
  ## Provide Values for Chart
  values:
    # controller.kind : DaemonSet
    # controller.daemonset.useHostPort : true
    # rbac.create : true

    version: 1.0.0
