apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: aws-credentials-route53
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: aws-credentials-route53
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: aws-credentials-route53