apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: miniapi-prod
spec:
  secretName: miniapi-production-certificate
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - "*.coacapp.de"
    - "*.heraeus.coacapp.de"