apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: saifty-flux
resources:
  - ./saifty_releases
  # - saifty_helm_repository.yaml
  # - rbac.yaml

patches:
  # Annotate all Saifty Specific releases
  - path: annotation_patch.yaml
    target:
      kind: HelmRelease
      annotationSelector: release_type=saifty_release
