---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: listener-operator
spec:
  interval: 30m # Check the changes in this release-file itself every 30 mins
  chart:
    spec:
      chart: listener-operator
      version: "23.7.0"
      sourceRef:
        kind: HelmRepository
        name: stackable-stable-repo
      interval: 12h # Check for changes in the Chart every 12h
      
  timeout: 40m # Installation of a component shouldn't exceed this

  values:

    csiProvisioner:
      resources:
        requests:
          cpu: 0m
          memory: 0Mi
        limits:
          cpu: 100m
          memory: 128Mi
    csiNodeDriverRegistrar:
      resources:
        requests:
          cpu: 0m
          memory: 0Mi
        limits:
          cpu: 100m
          memory: 128Mi

    controller:
      resources:
        # Resource requests and limits for the controller pod
        limits:
          cpu: 100m
          memory: 128Mi
        requests:
          cpu: 0m
          memory: 0Mi

    node:
      driver:
        resources:
          # Resource requests and limits for the per node driver container
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 0m
            memory: 0Mi