---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hive-operator
spec:
  interval: 30m # Check the changes in this release-file itself every 30 mins
  chart:
    spec:
      chart: hive-operator
      version: "23.7.0"
      sourceRef:
        kind: HelmRepository
        name: stackable-stable-repo
      interval: 12h # Check for changes in the Chart every 12h
      
  timeout: 40m # Installation of a component shouldn't exceed this
  dependsOn:
    - name: minio
  values:
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 0m
        memory: 0Mi