apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: not-important # Without including this, we encounter Error.

spec:
  interval: 30m
  chart:
    spec:
      sourceRef:
        kind: HelmRepository
        name: saifty-helm-repo
      interval: 12h
  
  timeout: 40m # Installation of a component shouldn't exceed this

  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true

  install:
    remediation:
      retries: 3
      remediateLastFailure: true