---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: secret-operator
spec:
  interval: 30m # Check the changes in this release-file itself every 30 mins
  chart:
    spec:
      chart: secret-operator
      version: "23.7.0"
      sourceRef:
        kind: HelmRepository
        name: stackable-stable-repo
      interval: 12h # Check for changes in the Chart every 12h
      
  timeout: 40m # Installation of a component shouldn't exceed this

  values:
    node:
      driver:
        # Resources of the secret-operator container itself
        resources:
          requests:
            # Putting Zero sets a default value internally. 
            cpu: 0m
            memory: 0Mi
    
    csiProvisioner:
      resources:
        requests:
          cpu: 0m
          memory: 0Mi

    csiNodeDriverRegistrar:
      resources:
        requests:
          cpu: 0m
          memory: 0Mi