apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: approvals
spec:
  chart:
    spec:
      chart: approvals
  ## MODIFY VALUES
  values:
    image:
      repository: 050565211916.dkr.ecr.eu-central-1.amazonaws.com/coac-bo-backend-core # {"$imagepolicy": "flux-system:approvals-image-policy:name"}
      tag: "1.2.68-release-282d75acaf-1727364956984" # {"$imagepolicy": "flux-system:approvals-image-policy:tag"}
    springCloudConfigEnabled: "false"
    dbCredentialSecret: "approvals.postgresql.credentials.postgresql.acid.zalan.do"
    packageSecretRef: "approvals-secrets"
    resources:
      limits:
        cpu: null
        memory: 3Gi
      requests:
        cpu: null
        memory: 0Mi
    # Ingress 
    ingress:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-production
        # kubernetes.io/tls-acme: "true"
      hosts:
        - host: approvals-dev.heraeus.coacapp.de
          paths:
            - path: "/"
              pathType: Prefix
      tls:
        - secretName: approvals-tls
          hosts:
            - approvals-dev.heraeus.coacapp.de
