apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: echa-dev
spec:
  chart:
    spec:
      chart: echa-dev
  ## MODIFY VALUES
  values:
    image:
      repository: 050565211916.dkr.ecr.eu-central-1.amazonaws.com/echa_crawler # {"$imagepolicy": "flux-system:echa-image-policy:name"}
      tag: "1.2.11-release-eedd9bb-1718267996" # {"$imagepolicy": "flux-system:echa-image-policy:tag"}
    ## Application Specific
    packageSecretRef: "echa-dev-secrets"
    dbCredentialSecret: ""
    resources:
      limits:
        cpu: null
        memory: 3Gi
      requests:
        cpu: null
        memory: 0Mi
    ## Ingress VAlues
    ingress:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-production
        # kubernetes.io/tls-acme: "true"
      hosts:
        - host: echa-dev.heraeus.coacapp.de
          paths:
            - path: "/"
              pathType: Prefix
      tls:
        - secretName: echa-tls
          hosts:
            - echa-dev.heraeus.coacapp.de
