apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  namespace: saifty-extraction-flux
  name: extraction
spec:
  chart:
    spec:
      chart: extraction
  ## MODIFT VALUES HERE ! 
  values:
    replicaCountApi: 2
    replicaCountWorker: 1
    ## .natsServerUrl , .prometheus-nats-exporter.config.nats, .prometheus-adapter.prometheus.url
    image:
      repository: 050565211916.dkr.ecr.eu-central-1.amazonaws.com/saifty-extraction # {"$imagepolicy": "flux-system:extraction-api-image-policy:name"}
      server_tag: 1.2.26-release-api-fb6b9b9-1730973240 # {"$imagepolicy": "flux-system:extraction-api-image-policy:tag"}
      worker_tag: 1.2.26-release-worker-fb6b9b9-1730973240 # {"$imagepolicy": "flux-system:extraction-worker-image-policy:tag"}
      pullPolicy: IfNotPresent
    dbCredentialSecret: "extraction.postgresql.credentials.postgresql.acid.zalan.do"
    packageSecretRef: "extraction-secrets"
    autoscaling:
      enabled: false
      minReplicas: 1
      maxReplicas: 5
      targetWorkerScalingVal: 3
      customNatsMetricsService: "nats-exporter-prometheus-nats-exporter"
      customMetricName: "jetstream_server_total_messages"
    resources:
      limits:
        cpu: null
        memory: 5Gi
      requests:
        cpu: null
        memory: 0Mi
    ## Ingress
    ingress:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-production
        # kubernetes.io/tls-acme: "true"
      hosts:
        - host: extraction-dev.heraeus.coacapp.de
          paths:
            - path: "/"
              pathType: Prefix
      tls:
        - secretName: extraction-tls
          hosts:
            - extraction-dev.heraeus.coacapp.de
