apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: federation-client
spec:
  chart:
    spec:
      chart: federation-client
  ## MODIFY VALUES
  values:
    image:
      repository: 050565211916.dkr.ecr.eu-central-1.amazonaws.com/federation-service-core # {"$imagepolicy": "flux-system:fed-client-image-policy:name"}
      tag: "1.2.11-release-80c11edc47-1718954834084" # {"$imagepolicy": "flux-system:fed-client-image-policy:tag"}
    packageSecretRef: "federation-client-secrets"
    ingress:
      enabled: false
    resources:
      limits:
        cpu: null
      requests:
        cpu: null
        memory: 0Mi
