apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: filestorage
spec:
  chart:
    spec:
      chart: filestorage
  ## MODIFT VALUES HERE !
  values:
    image:
      repository: "050565211916.dkr.ecr.eu-central-1.amazonaws.com/coac-filestorage-backend-core" # {"$imagepolicy": "flux-system:filestorage-image-policy:name"}
      tag: "1.2.22-release-d4f98d7285-1727332565942" # {"$imagepolicy": "flux-system:filestorage-image-policy:tag"}
    springCloudConfigEnabled: "false"
    dbCredentialSecret: "filestorage.postgresql.credentials.postgresql.acid.zalan.do"
    packageSecretRef: "filestorage-secrets"
    resources:
      limits:
        cpu: null
        memory: 1Gi
      requests:
        cpu: null
        memory: 0Mi
    ## Ingress
    ingress:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-production
        # kubernetes.io/tls-acme: "true"
      hosts:
        - host: filestorage-dev.heraeus.coacapp.de
          paths:
            - path: "/"
              pathType: Prefix
      tls:
        - secretName: filestorage-tls
          hosts:
            - filestorage-dev.heraeus.coacapp.de
