apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: saifty-phrases
spec:
  chart:
    spec:
      chart: saifty-phrases
  ## MODIFY VALUES
  values:
    replicaCount: 1
    imagePullPolicy: Always
    image:
      repository: 050565211916.dkr.ecr.eu-central-1.amazonaws.com/saifty-phrases-api # {"$imagepolicy": "flux-system:phrases-image-policy:name"}
      tag: "1.2.27-release-c5ac3250791-1730383353" # {"$imagepolicy": "flux-system:phrases-image-policy:tag"}
      #tag: "0.0.1-develop-2a8fa9764c9e1fa98ad5185d07e99ea64fe03ab3-1715084718"
    monolithUrl: "https://monolith-dev.heraeus.coacapp.de"
    packageSecretRef: "phrases-secrets"
    resources:
      limits:
        cpu: null
        memory: 8Gi
      requests:
        cpu: null
        memory: 0Mi
    # Ingress 
    ingress:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-production
        # kubernetes.io/tls-acme: "true"
      hosts:
        - host: phrases-dev.heraeus.coacapp.de
          paths:
            - path: "/"
              pathType: Prefix
      tls:
        - secretName: phrases-tls
          hosts:
            - phrases-dev.heraeus.coacapp.de
