apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: query-builder
spec:
  chart:
    spec:
      chart: query-builder
  ## MODIFY VALUES
  values:
    image:
      repository: 050565211916.dkr.ecr.eu-central-1.amazonaws.com/saifty-query-builder 
      tag: "a616eb402bc3353f0988074079e0202ea72c31f5"
    dbCredentialSecret: "query-builder.postgresql.credentials.postgresql.acid.zalan.do"
    packageSecretRef: "query-builder-secrets"
    resources:
      limits:
        cpu: null
      requests:
        cpu: null
        memory: 0Mi
    # Ingress 
    ingress:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-production
        # kubernetes.io/tls-acme: "true"
      hosts:
        - host: query-builder-dev.heraeus.coacapp.de
          paths:
            - path: "/"
              pathType: Prefix
      tls:
        - secretName: query-builder-tls
          hosts:
            - query-builder-dev.heraeus.coacapp.de
