apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# Any resource inside this kustomization 
# will be in default ! 
# unless hardcoded inside yaml
namespace: default
resources:
  - ../../base
  # - custom_nginx_configs.yaml
patches:
- path: nginx-values.yaml
  target:
    kind: HelmRelease