---
apiVersion: v1
kind: Service
metadata:
  name: nifi-lb
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  selector:
    app.kubernetes.io/instance: simple-nifi
  ports:
    - name: tcp-port
      protocol: TCP
      port: 8443
      targetPort: 8443

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "nifi-heraeus-dev-ing"
  namespace: saifty-flux
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  ingressClassName: nginx
  rules:
    - host: "nifi-dev.heraeus.coacapp.de"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: simple-nifi
                port:
                  number: 8443

  tls:
    - hosts:
        - "nifi-dev.heraeus.coacapp.de"
      secretName: nifi-heraeus-dev-tls